name: Discord Bot 
on:
    push:
      branches:
        - main
env:
 TOKEN: ${{ secrets.TOKEN }}
 OWNERID: ${{ secrets.OWNERID }}
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Cache Stuff
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
        - name: Start Bot
          run: |
            python bot.py
          
